### PR TITLE
Add configurable timeout for transaction's  BEGIN/COMMIT/ROLLBACK

### PR DESCRIPTION
**Pull request by seriyps**
Maybe you can suggest a better option name

### CODE REVIEW

**Comment by yzh44yzh** [comment]
'transaction_timeout' is good enough

**Comment by seriyps** [comment]
In my opinion, `transaction_timeout` may be interpreted as "timeout for whole transaction". But will not insist.

**Comment by seriyps** [comment]
Updated

**Comment by yzh44yzh** [comment]
thanks

**Pull request merged**
